[workspace]
members = [
    "infrastructure/core",
    "infrastructure/optimization",
    "infrastructure/observatory/api",
    "financial/ese",
    "financial/strategies",
    "financial/core",
    "coralys-moga",
    "coralys-simulation",
    "coralys-ecology",
    "coralys-decision",
    "coralys-recommendation",
    "coralys-infrastructure",
    "adapters/ultracrew",
    "adapters/chronosentiment",
    "adapters/cvrp", "coralys-v2",
    "coralys-core",
    "coralys-matching",
    "adapters/roadef",
    "services/ultracrew_server",
    "services/cvrp_server",
]
resolver = "2"
