[workspace]
members = [
    "infrastructure/core",
    "infrastructure/optimization",
    "infrastructure/observatory/api",
    "financial/ese",
    "financial/strategies",
    "financial/core",
    "coralys-moga",
    "coralys-simulation",
    "coralys-ecology",
    "coralys-decision",
    "coralys-recommendation",
    "coralys-infrastructure",
    "adapters/ultracrew",
    "adapters/chronosentiment",
    "adapters/ultracrew",
    "adapters/chronosentiment",
]
resolver = "2"
