[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
tokio = { version = "1.37.0", features = ["full"] }
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
uuid = { version = "1.8.0", features = ["v4", "serde"] }
env_logger = "0.11.3"
log = "0.4.21"
tower-http = { version = "0.5", features = ["cors"] }
rand = "0.8.5"
blake3 = "1.5.0"

chronosentiment_core = { path = "../../core" }
chronosentiment_strategies = { version = "0.1.0", path = "../../../financial/strategies" }
chronosentiment_optimization = { version = "0.1.0", path = "../../optimization" }

[features]
debug_decision = ["chronosentiment_core/debug_decision"]
