use coralys_ecology::diagnostics::EcologyState;
use coralys_recommendation::RecommendationReport;
use serde::{Deserialize, Serialize};

/// Decision emitted by the policy layer in response to a recommendation report.
///
/// `rationales` is a `Vec<String>` (not a single string) so that the full
/// evidence chain from Diagnostics → Recommendation → Decision is preserved
/// and queryable independently.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct PolicyDecision {
    /// The chosen governance action (e.g. "Reserve archive slots for target-improving solutions").
    pub action: String,
    /// Confidence in this decision, inherited from the backing recommendation (0.0–1.0).
    pub confidence: f64,
    /// One or more human-readable rationales explaining the decision.
    /// Multiple entries preserve the diagnostic → recommendation → decision chain.
    pub rationales: Vec<String>,
}

/// Core policy engine trait.
///
/// Implementations must be read-only — they may not mutate `EcologyState`,
/// `RecommendationReport`, or any MOGA search parameters.
pub trait PolicyEngine {
    fn evaluate(&self, state: &EcologyState, report: &RecommendationReport) -> PolicyDecision;
}

/// A passive policy that mirrors the first recommendation.
///
/// This is intentionally not called `PassivePolicy` because future policies
/// may also be passive but behave differently (e.g. `ConfidenceWeightedPolicy`,
/// `ConsensusPolicy`). The name communicates *what* this policy does, not merely
/// *how* it behaves.
///
/// It does **not** modify any search parameters or call back into MOGA.
pub struct RecommendationMirrorPolicy;

impl PolicyEngine for RecommendationMirrorPolicy {
    fn evaluate(&self, _state: &EcologyState, report: &RecommendationReport) -> PolicyDecision {
        if let Some(first) = report.recommendations.first() {
            PolicyDecision {
                action: first.action.clone(),
                confidence: first.confidence,
                rationales: vec![
                    first.rationale.clone(),
                    format!("Evidence: {}", first.evidence.join("; ")),
                ],
            }
        } else {
            PolicyDecision {
                action: "No Action".to_string(),
                confidence: 0.0,
                rationales: vec!["No recommendations were generated by the ecology layer.".to_string()],
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use coralys_recommendation::{InterventionRecommendation, RecommendationReport};
    use coralys_ecology::diagnostics::EcologyState;

    fn make_report(action: &str, rationale: &str, confidence: f64) -> RecommendationReport {
        RecommendationReport {
            generated_at_generation: 100,
            recommendations: vec![InterventionRecommendation {
                action: action.to_string(),
                rationale: rationale.to_string(),
                confidence,
                evidence: vec!["rejection_rate = 0.8900".to_string()],
            }],
        }
    }

    #[test]
    fn test_mirror_policy_mirrors_first_recommendation() {
        let state = EcologyState::new(10);
        let report = make_report(
            "Reserve archive slots for target-improving solutions",
            "Target-improving candidates are being rejected at a high rate.",
            0.89,
        );
        let policy = RecommendationMirrorPolicy;
        let decision = policy.evaluate(&state, &report);

        assert_eq!(decision.action, "Reserve archive slots for target-improving solutions");
        assert!((decision.confidence - 0.89).abs() < 1e-9);
        assert_eq!(decision.rationales.len(), 2);
        assert!(decision.rationales[0].contains("rejected"));
        assert!(decision.rationales[1].starts_with("Evidence:"));
    }

    #[test]
    fn test_mirror_policy_no_recommendations() {
        let state = EcologyState::new(10);
        let report = RecommendationReport {
            generated_at_generation: 0,
            recommendations: vec![],
        };
        let policy = RecommendationMirrorPolicy;
        let decision = policy.evaluate(&state, &report);

        assert_eq!(decision.action, "No Action");
        assert!((decision.confidence - 0.0).abs() < 1e-9);
        assert_eq!(decision.rationales.len(), 1);
    }

    #[test]
    fn test_policy_decision_serialization() {
        let decision = PolicyDecision {
            action: "Test Action".to_string(),
            confidence: 0.75,
            rationales: vec!["Reason A".to_string(), "Reason B".to_string()],
        };
        let json = serde_json::to_string(&decision).unwrap();
        let parsed: PolicyDecision = serde_json::from_str(&json).unwrap();
        assert_eq!(decision, parsed);
    }

    #[test]
    fn test_policy_decision_preserves_multiple_rationales() {
        let decision = PolicyDecision {
            action: "Diversify".to_string(),
            confidence: 0.6,
            rationales: vec![
                "AccumulationFailure confidence 0.89".to_string(),
                "Evidence: rejection_rate = 0.89".to_string(),
                "Trend sustained over 100 generations".to_string(),
            ],
        };
        assert_eq!(decision.rationales.len(), 3);
    }
}
