# scripts/build_session_catalog.py
"""Build the session catalog from a validated batch of Kite captures.
- Reads per‑session validation reports generated by `validate_corpus.py`.
- Only sessions marked as valid are included.
- Processes dates in chronological order, keeping track of the previous
  closing price for each symbol to compute `gap_pct`.
- Writes a single JSON array to the path supplied by the user.
"""
import json
import sys
from pathlib import Path
from typing import Dict, Any, List

from session_metrics import compute_all

def load_validation_report(report_path: Path) -> dict:
    try:
        return json.loads(report_path.read_text())
    except Exception as e:
        return {"valid": False, "issues": [f"load error: {e}"]}

def main(batch_root: str, output_path: str):
    root = Path(batch_root)
    if not root.is_dir():
        sys.exit(f"[!] Batch root {batch_root} does not exist or is not a directory")

    # Gather all session directories sorted chronologically
    session_dirs = sorted([p for p in root.iterdir() if p.is_dir()], key=lambda p: p.name)
    catalog: List[Dict[str, Any]] = []
    prev_close: Dict[str, float] = {}

    for session_dir in session_dirs:
        date_str = session_dir.name
        # For each symbol, check the validation report
        for report_file in session_dir.glob("validation_report_*.json"):
            symbol = report_file.stem.replace("validation_report_", "")
            report = load_validation_report(report_file)
            if not report.get("valid", False):
                continue  # skip invalid sessions
            # Paths needed for metrics
            canon_path = session_dir / "canonical" / f"{symbol}_1m.csv"
            manifest_path = session_dir / "capture_manifest.json"
            manifest = json.loads(manifest_path.read_text())
            manifest_entry = manifest["symbols"][symbol]
            manifest_sha = manifest_entry.get("canonical_1m_sha256") or ""
            # Compute metrics, passing previous day's close if available
            metrics = compute_all(
                csv_path=canon_path,
                manifest_sha256=manifest_sha,
                prev_close=prev_close.get(symbol)
            )
            # After metrics, store today's close for next day's gap calculation
            prev_close[symbol] = metrics["close"]
            # Assemble catalog entry
            entry = {
                "date": date_str,
                "symbol": symbol,
                "open": metrics["open"],
                "high": metrics["high"],
                "low": metrics["low"],
                "close": metrics["close"],
                "gap_pct": metrics["gap_pct"],
                "realized_volatility": metrics["realized_volatility"],
                "trend_strength": metrics["trend_strength"],
                "session_range_pct": metrics["session_range_pct"],
                "net_return_pct": metrics["net_return_pct"],
                "candle_count": metrics["candle_count"],
                "missing_candles": metrics["missing_candles"],
                "duplicate_timestamps": metrics["duplicate_timestamps"],
                "manifest_sha256": metrics["manifest_sha256"],
            }
            catalog.append(entry)

    # Write catalog JSON (pretty‑printed array)
    out_path = Path(output_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(catalog, indent=2))
    print(f"[INFO] Session catalog written to {out_path} ({len(catalog)} entries)")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Build session catalog from validated Kite batch")
    parser.add_argument("--input-dir", required=True, help="Root of the batch capture (historical_capture/batch)")
    parser.add_argument("--output", required=True, help="Path to write session_catalog.json")
    args = parser.parse_args()
    main(args.input_dir, args.output)
