#!/usr/bin/env python3
"""Minimal historical capture using Zerodha Kite Connect.

Purpose
-------
- Resolve instrument tokens at runtime (no hard‑coded values).
- Fetch 1‑minute candles for a given date (single trading session).
- Produce the same provenance artifacts as the live‑capture pipeline:
  * raw JSON
  * canonical 1‑minute CSV
  * derived 5‑minute CSV
  * capture_manifest.json (mirrors live‑capture schema plus `instrument_token`).

Usage example
-------------
    python3 scripts/kite_historical_minimal.py \
        --symbols NIFTY BANKNIFTY \
        --date 2025-01-01 \
        --output-dir historical_capture

All credentials must be provided via environment variables:
    KITE_API_KEY, KITE_API_SECRET
The access token must be present in `kite_access_token.txt` (generated by `kite_test_auth.py`).
"""
import os
import sys
import json
import hashlib
import datetime as dt
from pathlib import Path
import pandas as pd

# Local imports
import sys
from pathlib import Path
# Add the scripts directory to PYTHONPATH so we can import kite_utils directly
script_dir = Path(__file__).parent
sys.path.append(str(script_dir))
from kite_utils import get_token
# Add repository root for live capture utilities
sys.path.append(str(Path(__file__).parent.parent))
from scripts.live.live_capture_yahoo import derive_5m

# Helper for SHA‑256
def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()

def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())

def fetch_day(symbol: str, token: int, date_str: str, kite, max_retries=3, timeout=30):
    """Fetch 1‑minute candles for *symbol* on *date_str* (YYYY‑MM‑DD).
    Retries up to *max_retries* with a longer *timeout* (seconds).
    """
    from_dt = f"{date_str} 09:15:00"
    to_dt = f"{date_str} 15:30:00"
    for attempt in range(1, max_retries + 1):
        try:
            kite.timeout = timeout  # set per‑request timeout
            return kite.historical_data(
                instrument_token=token,
                from_date=from_dt,
                to_date=to_dt,
                interval="minute",
            )
        except Exception as e:
            if attempt == max_retries:
                raise
            print(f"[WARN] fetch_day attempt {attempt} failed ({e}); retrying...")


def main(symbols, date_str, output_root):
    # Prepare output directories
    session_dir = Path(output_root) / date_str
    raw_dir = session_dir / "raw"
    canon_dir = session_dir / "canonical"
    derived_dir = session_dir / "derived"
    for d in (raw_dir, canon_dir, derived_dir):
        d.mkdir(parents=True, exist_ok=True)

    # Initialise Kite client (credentials are already validated in kite_utils)
    from kiteconnect import KiteConnect
    API_KEY = os.getenv("KITE_API_KEY")
    ACCESS_TOKEN_PATH = Path("kite_access_token.txt")
    ACCESS_TOKEN = ACCESS_TOKEN_PATH.read_text().strip()
    kite = KiteConnect(api_key=API_KEY)
    kite.set_access_token(ACCESS_TOKEN)

    manifest = {
        "session_id": f"KITE_{date_str}",
        "capture_date": date_str,
        "capture_start_utc": dt.datetime.utcnow().isoformat() + "Z",
        "script_version": "1.0.0",
        "provider": "Zerodha Kite",
        "symbols": {}
    }

    for sym in symbols:
        token = get_token(sym)
        raw_records = fetch_day(sym, token, date_str, kite)
        if not raw_records:
            print(f"[WARN] No records fetched for {sym} on {date_str}; skipping canonical/derived generation.")
            continue
        # ----- Raw JSON -----
        raw_path = raw_dir / f"{sym}.json"
        raw_content = {"symbol": sym, "records": raw_records}
        raw_path.write_text(json.dumps(raw_content, indent=2, default=str))
        raw_hash = sha256_file(raw_path)
        # ----- Canonical CSV -----
        df = pd.DataFrame(raw_records)
        # Convert the "date" field (datetime with tz) to ISO UTC string
        df["timestamp"] = pd.to_datetime(df["date"]).dt.tz_convert("UTC").dt.strftime("%Y-%m-%dT%H:%M:%SZ")
        canon_path = canon_dir / f"{sym}_1m.csv"
        df[["timestamp", "open", "high", "low", "close", "volume"]].to_csv(canon_path, index=False)
        canon_hash = sha256_file(canon_path)
        # ----- Derived 5‑minute CSV -----
        derived_df = derive_5m(pd.read_csv(canon_path))
        derived_path = derived_dir / f"{sym}_5m.csv"
        derived_df.to_csv(derived_path, index=False)
        derived_hash = sha256_file(derived_path)
        # ----- Manifest entry -----
        manifest["symbols"][sym] = {
            "provider_symbol": sym,
            "instrument_token": token,
            "raw_json_path": str(raw_path),
            "raw_json_sha256": raw_hash,
            "canonical_1m_path": str(canon_path),
            "canonical_1m_sha256": canon_hash,
            "derived_5m_path": str(derived_path),
            "derived_5m_sha256": derived_hash,
            "retrieval_method": "kiteconnect",
            "capture_timestamp_utc": dt.datetime.utcnow().isoformat() + "Z",
            "script_version": "1.0.0"
        }
        print(f"[{sym}] fetched {len(raw_records)} candles for {date_str}")

    manifest["capture_end_utc"] = dt.datetime.utcnow().isoformat() + "Z"
    manifest_path = session_dir / "capture_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2))
    print(f"Capture manifest written to {manifest_path}")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Minimal historical capture via Kite Connect")
    parser.add_argument("--symbols", nargs="+", required=True, help="Symbols to capture (e.g., NIFTY BANKNIFTY)")
    parser.add_argument("--date", required=True, help="Trading date in YYYY-MM-DD format")
    parser.add_argument("--output-dir", default="historical_capture", help="Root directory for captured session")
    args = parser.parse_args()
    # Basic validation of date format
    try:
        dt.datetime.strptime(args.date, "%Y-%m-%d")
    except ValueError:
        sys.exit("[!] Invalid date format. Use YYYY-MM-DD.")
    main(args.symbols, args.date, args.output_dir)
