#!/usr/bin/env python3
"""Utility functions for Zerodha Kite Connect.
All credentials are read from environment variables:
    KITE_API_KEY
    KITE_API_SECRET
Access token must be present in 'kite_access_token.txt' (generated by kite_test_auth.py).
The module provides a single helper to resolve an instrument token for a given symbol
(e.g., "NIFTY" or "BANKNIFTY") at runtime, avoiding hard‑coded values.
"""
import os
import json
import sys
from pathlib import Path
from kiteconnect import KiteConnect

# Load access token (generated by kite_test_auth.py)
TOKEN_PATH = Path("kite_access_token.txt")
if not TOKEN_PATH.is_file():
    sys.exit("[!] Access token file 'kite_access_token.txt' not found. Run kite_test_auth.py first.")
with TOKEN_PATH.open() as f:
    ACCESS_TOKEN = f.read().strip()

# Initialise Kite client using env vars
API_KEY = os.getenv("KITE_API_KEY") or "YOUR_API_KEY"
API_SECRET = os.getenv("KITE_API_SECRET") or "YOUR_API_SECRET"
if API_KEY == "YOUR_API_KEY" or API_SECRET == "YOUR_API_SECRET":
    sys.exit("[!] Set KITE_API_KEY and KITE_API_SECRET in the environment before using kite_utils.")

kite = KiteConnect(api_key=API_KEY)
kite.set_access_token(ACCESS_TOKEN)

def get_token(symbol: str) -> int:
    """Resolve the instrument token for *symbol*.
    First checks a hard‑coded fallback map for common index symbols (NIFTY, BANKNIFTY).
    If not found, queries the Kite "instrument" endpoint.
    Raises ValueError if the symbol cannot be resolved.
    """
    # Known index symbols and their tokens (pre‑validated for this account)
    fallback = {
        "NIFTY": 256265,
        "BANKNIFTY": 260105,
    }
    if symbol in fallback:
        return fallback[symbol]
    # The "instruments" call returns a list of dictionaries describing all tradable instruments.
    # It can be filtered by exchange, but we keep it simple and scan the full list.
    try:
        instruments = kite.instruments()
    except Exception as e:
        raise RuntimeError(f"Failed to fetch instrument list from Kite: {e}")
    for instr in instruments:
        if instr.get("tradingsymbol") == symbol:
            token = instr.get("instrument_token")
            if token is None:
                continue
            return int(token)
    raise ValueError(f"Instrument token for symbol '{symbol}' not found in Kite instrument list.")

def list_available_symbols() -> list[str]:
    """Return a list of all tradable symbol strings (e.g., NIFTY, BANKNIFTY)."""
    try:
        instruments = kite.instruments()
    except Exception as e:
        raise RuntimeError(f"Failed to fetch instrument list from Kite: {e}")
    return sorted({instr.get("tradingsymbol") for instr in instruments if instr.get("tradingsymbol")})

if __name__ == "__main__":
    # Simple CLI for quick debugging
    if len(sys.argv) != 2:
        print("Usage: python kite_utils.py SYMBOL")
        sys.exit(1)
    sym = sys.argv[1]
    try:
        token = get_token(sym)
        print(f"Instrument token for {sym}: {token}")
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)

