import json
import os
from pathlib import Path
from datetime import datetime

def build_catalog():
    chronology_dir = Path("core/chronology")
    catalog_md_path = chronology_dir / "CHRONOLOGY_CATALOG.md"
    catalog_json_path = chronology_dir / "catalog.json"
    
    entries = []

    # Traverse all directories looking for manifests
    for root, dirs, files in os.walk(chronology_dir):
        for file in files:
            if file.endswith("_manifest.json"):
                manifest_path = Path(root) / file
                with open(manifest_path, "r") as f:
                    try:
                        data = json.load(f)
                    except json.JSONDecodeError:
                        continue
                        
                # Determine provenance
                if "live_capture" in root:
                    provenance = "Live WebSocket"
                    name = "live_rotation_" + str(data.get("capture_start", "unknown"))
                elif "historical" in root:
                    provenance = "Historical REST API"
                    name = Path(root).name
                else:
                    provenance = "Unknown"
                    name = "unknown"

                start_ts = data.get("capture_start") or data.get("start_timestamp")
                end_ts = data.get("capture_end") or data.get("end_timestamp")
                
                if start_ts:
                    start_date = datetime.fromtimestamp(start_ts / 1000).strftime('%Y-%m-%d %H:%M:%S UTC') if start_ts > 1e11 else datetime.fromtimestamp(start_ts).strftime('%Y-%m-%d %H:%M:%S UTC')
                else:
                    start_date = "Unknown"

                entries.append({
                    "name": name,
                    "substrate": data.get("substrate", "UNKNOWN"),
                    "provenance": provenance,
                    "start_date": start_date,
                    "total_ticks": data.get("total_ticks", data.get("total_klines", 0)),
                    "gaps_recorded": len(data.get("gaps", [])),
                    "chronology_hash": data.get("chronology_hash", "UNKNOWN")
                })
                
    # Sort entries by name
    entries.sort(key=lambda x: x["name"])

    # Write JSON
    with open(catalog_json_path, "w") as f:
        json.dump({"universes": entries}, f, indent=4)

    # Write Markdown
    with open(catalog_md_path, "w") as f:
        f.write("# CHRONOLOGY CATALOG\n\n")
        f.write("This document is an autogenerated index of all immutable chronology universes currently preserved in the observatory.\n\n")
        
        f.write("| Universe Name | Substrate | Provenance | Capture Start | Ticks | Gaps | Hash (Truncated) |\n")
        f.write("|---|---|---|---|---|---|---|\n")
        
        for e in entries:
            trunc_hash = e["chronology_hash"][:12] + "..." if len(e["chronology_hash"]) > 12 else e["chronology_hash"]
            f.write(f"| `{e['name']}` | {e['substrate']} | {e['provenance']} | {e['start_date']} | {e['total_ticks']} | {e['gaps_recorded']} | `{trunc_hash}` |\n")

    print(f"✅ Rebuilt Chronology Catalog with {len(entries)} universes.")
    print(f"Outputs:\n - {catalog_md_path}\n - {catalog_json_path}")

if __name__ == "__main__":
    build_catalog()
